server {
    server_name dientempo.bystruev.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /var/www/dientempo.bystruev.com/html;
        try_files $uri $uri/ =404;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/dientempo.bystruev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dientempo.bystruev.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = dientempo.bystruev.com) {
        return 301 https://$host$request_uri;
    }

    server_name dientempo.bystruev.com;
    listen 80;
    return 404;
}
